/**
 * AI Adapter Fallback プロパティテスト
 *
 * Property 15: AI Adapter Fallback
 * - プライマリアダプタが失敗した場合、システムは設定されたフォールバックアダプタを
 *   使用してから失敗を報告すること
 *
 * **Validates: Requirements 7.5**
 *
 * @module tests/adapters/adapter-fallback.property.test
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fc from 'fast-check';
import {
  BaseAdapter,
  ExtendedAdapter,
  GenerateOptions,
  ChatOptions,
  ChatWithToolsOptions,
  AdapterResponse,
  ToolCallResponse,
  ToolDefinition,
  ModelInfo,
  AdapterConnectionError,
  AdapterFallbackError,
} from '../../tools/adapters/base';
import {
  AdapterRegistry,
  FallbackAdapter,
  createAdapterFromConfig,
} from '../../tools/adapters/index';

// =============================================================================
// テスト用モックアダプタ
// =============================================================================

/**
 * 成功するモックアダプタ
 */
class SuccessAdapter implements ExtendedAdapter {
  readonly name: string;
  private callCount = 0;

  constructor(name: string = 'success-adapter') {
    this.name = name;
  }

  async generate(options: GenerateOptions): Promise<AdapterResponse> {
    this.callCount++;
    return {
      content: `Generated by ${this.name}: ${options.prompt}`,
      model: options.model,
      tokensUsed: 10,
      finishReason: 'stop',
    };
  }

  async chat(options: ChatOptions): Promise<AdapterResponse> {
    this.callCount++;
    const lastMessage = options.messages[options.messages.length - 1];
    return {
      content: `Chat response from ${this.name}: ${lastMessage.content}`,
      model: options.model,
      tokensUsed: 15,
      finishReason: 'stop',
    };
  }

  async chatWithTools(options: ChatWithToolsOptions): Promise<ToolCallResponse> {
    this.callCount++;
    return {
      content: `Tool response from ${this.name}`,
      model: options.model,
      tokensUsed: 20,
      finishReason: 'stop',
      toolCalls: [],
      isComplete: true,
    };
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async getModelInfo(): Promise<ModelInfo> {
    return {
      name: this.name,
      description: 'Test adapter',
      supportsTools: true,
      contextWindow: 4096,
    };
  }

  supportsTools(): boolean {
    return true;
  }

  getCallCount(): number {
    return this.callCount;
  }

  resetCallCount(): void {
    this.callCount = 0;
  }
}

/**
 * 常に失敗するモックアダプタ
 */
class FailingAdapter implements ExtendedAdapter {
  readonly name: string;
  private callCount = 0;

  constructor(name: string = 'failing-adapter') {
    this.name = name;
  }

  async generate(_options: GenerateOptions): Promise<AdapterResponse> {
    this.callCount++;
    throw new AdapterConnectionError(`${this.name} connection failed`);
  }

  async chat(_options: ChatOptions): Promise<AdapterResponse> {
    this.callCount++;
    throw new AdapterConnectionError(`${this.name} connection failed`);
  }

  async chatWithTools(_options: ChatWithToolsOptions): Promise<ToolCallResponse> {
    this.callCount++;
    throw new AdapterConnectionError(`${this.name} connection failed`);
  }

  async isAvailable(): Promise<boolean> {
    return false;
  }

  async getModelInfo(): Promise<ModelInfo> {
    return {
      name: this.name,
      description: 'Failing test adapter',
      supportsTools: true,
      contextWindow: 4096,
    };
  }

  supportsTools(): boolean {
    return true;
  }

  getCallCount(): number {
    return this.callCount;
  }

  resetCallCount(): void {
    this.callCount = 0;
  }
}

/**
 * N回失敗してから成功するモックアダプタ
 */
class IntermittentAdapter implements ExtendedAdapter {
  readonly name: string;
  private callCount = 0;
  private failuresBeforeSuccess: number;

  constructor(name: string = 'intermittent-adapter', failuresBeforeSuccess: number = 2) {
    this.name = name;
    this.failuresBeforeSuccess = failuresBeforeSuccess;
  }

  async generate(options: GenerateOptions): Promise<AdapterResponse> {
    this.callCount++;
    if (this.callCount <= this.failuresBeforeSuccess) {
      throw new AdapterConnectionError(`${this.name} temporary failure (attempt ${this.callCount})`);
    }
    return {
      content: `Generated after ${this.callCount} attempts`,
      model: options.model,
      tokensUsed: 10,
      finishReason: 'stop',
    };
  }

  async chat(options: ChatOptions): Promise<AdapterResponse> {
    this.callCount++;
    if (this.callCount <= this.failuresBeforeSuccess) {
      throw new AdapterConnectionError(`${this.name} temporary failure (attempt ${this.callCount})`);
    }
    return {
      content: `Chat response after ${this.callCount} attempts`,
      model: options.model,
      tokensUsed: 15,
      finishReason: 'stop',
    };
  }

  async chatWithTools(options: ChatWithToolsOptions): Promise<ToolCallResponse> {
    this.callCount++;
    if (this.callCount <= this.failuresBeforeSuccess) {
      throw new AdapterConnectionError(`${this.name} temporary failure (attempt ${this.callCount})`);
    }
    return {
      content: `Tool response after ${this.callCount} attempts`,
      model: options.model,
      tokensUsed: 20,
      finishReason: 'stop',
      toolCalls: [],
      isComplete: true,
    };
  }

  async isAvailable(): Promise<boolean> {
    return this.callCount > this.failuresBeforeSuccess;
  }

  async getModelInfo(): Promise<ModelInfo> {
    return {
      name: this.name,
      description: 'Intermittent test adapter',
      supportsTools: true,
      contextWindow: 4096,
    };
  }

  supportsTools(): boolean {
    return true;
  }

  getCallCount(): number {
    return this.callCount;
  }

  resetCallCount(): void {
    this.callCount = 0;
  }
}

// =============================================================================
// ジェネレータ（Arbitrary）定義
// =============================================================================

/**
 * 有効なモデル名を生成するArbitrary
 */
const modelNameArb: fc.Arbitrary<string> = fc.constantFrom(
  'llama3',
  'llama3.1',
  'mistral',
  'codellama',
  'qwen2',
  'gpt-4',
  'claude-3'
);

/**
 * 有効なプロンプトを生成するArbitrary
 */
const promptArb: fc.Arbitrary<string> = fc.string({ minLength: 1, maxLength: 500 });

/**
 * GenerateOptionsを生成するArbitrary
 */
const generateOptionsArb: fc.Arbitrary<GenerateOptions> = fc.record({
  model: modelNameArb,
  prompt: promptArb,
  system: fc.option(fc.string({ minLength: 1, maxLength: 200 }), { nil: undefined }),
  temperature: fc.option(fc.double({ min: 0, max: 1 }), { nil: undefined }),
  maxTokens: fc.option(fc.integer({ min: 100, max: 4096 }), { nil: undefined }),
});

/**
 * ChatMessageを生成するArbitrary
 */
const chatMessageArb = fc.record({
  role: fc.constantFrom('system', 'user', 'assistant') as fc.Arbitrary<'system' | 'user' | 'assistant'>,
  content: fc.string({ minLength: 1, maxLength: 300 }),
});

/**
 * ChatOptionsを生成するArbitrary
 */
const chatOptionsArb: fc.Arbitrary<ChatOptions> = fc.record({
  model: modelNameArb,
  messages: fc.array(chatMessageArb, { minLength: 1, maxLength: 10 }),
  temperature: fc.option(fc.double({ min: 0, max: 1 }), { nil: undefined }),
  maxTokens: fc.option(fc.integer({ min: 100, max: 4096 }), { nil: undefined }),
});

/**
 * ToolDefinitionを生成するArbitrary
 */
const toolDefinitionArb: fc.Arbitrary<ToolDefinition> = fc.record({
  name: fc.stringOf(fc.constantFrom(...'abcdefghijklmnopqrstuvwxyz_'.split('')), {
    minLength: 3,
    maxLength: 30,
  }),
  description: fc.string({ minLength: 10, maxLength: 200 }),
  parameters: fc.constant({
    type: 'object' as const,
    properties: {
      input: { type: 'string' as const, description: 'Input parameter' },
    },
    required: ['input'],
  }),
});

/**
 * ChatWithToolsOptionsを生成するArbitrary
 */
const chatWithToolsOptionsArb: fc.Arbitrary<ChatWithToolsOptions> = fc.record({
  model: modelNameArb,
  messages: fc.array(chatMessageArb, { minLength: 1, maxLength: 5 }),
  tools: fc.array(toolDefinitionArb, { minLength: 1, maxLength: 3 }),
  temperature: fc.option(fc.double({ min: 0, max: 1 }), { nil: undefined }),
  maxTokens: fc.option(fc.integer({ min: 100, max: 4096 }), { nil: undefined }),
});

/**
 * リトライ回数を生成するArbitrary
 */
const maxRetriesArb: fc.Arbitrary<number> = fc.integer({ min: 1, max: 5 });

/**
 * リトライ遅延を生成するArbitrary（テスト用に短い値）
 */
const retryDelayArb: fc.Arbitrary<number> = fc.integer({ min: 10, max: 100 });

// =============================================================================
// Property 15: AI Adapter Fallback テスト
// =============================================================================

describe('Property 15: AI Adapter Fallback', () => {
  let primaryAdapter: FailingAdapter;
  let fallbackAdapter: SuccessAdapter;
  let fallbackAdapterInstance: FallbackAdapter;

  beforeEach(() => {
    primaryAdapter = new FailingAdapter('primary');
    fallbackAdapter = new SuccessAdapter('fallback');
    fallbackAdapterInstance = new FallbackAdapter(primaryAdapter, fallbackAdapter, {
      maxRetries: 3,
      retryDelayMs: 10, // テスト用に短い遅延
    });
  });

  afterEach(() => {
    primaryAdapter.resetCallCount();
    fallbackAdapter.resetCallCount();
  });

  /**
   * Property 15.1: プライマリアダプタが失敗した場合、フォールバックアダプタが使用される
   *
   * *For any* AI request where the primary adapter fails, the system SHALL
   * attempt to use the configured fallback adapter before reporting failure.
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.1: プライマリアダプタが失敗した場合、フォールバックアダプタが使用される（generate）', async () => {
    await fc.assert(
      fc.asyncProperty(generateOptionsArb, async (options) => {
        // フォールバックアダプタで生成を実行
        const result = await fallbackAdapterInstance.generate(options);

        // 検証: フォールバックアダプタが使用されたこと
        expect(result.content).toContain('fallback');

        // 検証: プライマリアダプタが試行されたこと（リトライ回数分）
        expect(primaryAdapter.getCallCount()).toBe(3);

        // 検証: フォールバックアダプタが呼び出されたこと
        expect(fallbackAdapter.getCallCount()).toBe(1);

        // リセット
        primaryAdapter.resetCallCount();
        fallbackAdapter.resetCallCount();
      }),
      { numRuns: 50 }
    );
  });

  /**
   * Property 15.2: プライマリアダプタが失敗した場合、フォールバックアダプタが使用される（chat）
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.2: プライマリアダプタが失敗した場合、フォールバックアダプタが使用される（chat）', async () => {
    await fc.assert(
      fc.asyncProperty(chatOptionsArb, async (options) => {
        // フォールバックアダプタでチャットを実行
        const result = await fallbackAdapterInstance.chat(options);

        // 検証: フォールバックアダプタが使用されたこと
        expect(result.content).toContain('fallback');

        // 検証: プライマリアダプタが試行されたこと
        expect(primaryAdapter.getCallCount()).toBe(3);

        // 検証: フォールバックアダプタが呼び出されたこと
        expect(fallbackAdapter.getCallCount()).toBe(1);

        // リセット
        primaryAdapter.resetCallCount();
        fallbackAdapter.resetCallCount();
      }),
      { numRuns: 50 }
    );
  });

  /**
   * Property 15.3: プライマリアダプタが失敗した場合、フォールバックアダプタが使用される（chatWithTools）
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.3: プライマリアダプタが失敗した場合、フォールバックアダプタが使用される（chatWithTools）', async () => {
    await fc.assert(
      fc.asyncProperty(chatWithToolsOptionsArb, async (options) => {
        // フォールバックアダプタでツール付きチャットを実行
        const result = await fallbackAdapterInstance.chatWithTools(options);

        // 検証: フォールバックアダプタが使用されたこと
        expect(result.content).toContain('fallback');

        // 検証: プライマリアダプタが試行されたこと
        expect(primaryAdapter.getCallCount()).toBe(3);

        // 検証: フォールバックアダプタが呼び出されたこと
        expect(fallbackAdapter.getCallCount()).toBe(1);

        // リセット
        primaryAdapter.resetCallCount();
        fallbackAdapter.resetCallCount();
      }),
      { numRuns: 50 }
    );
  });

  /**
   * Property 15.4: プライマリとフォールバック両方が失敗した場合、AdapterFallbackErrorが投げられる
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.4: プライマリとフォールバック両方が失敗した場合、AdapterFallbackErrorが投げられる', async () => {
    const bothFailingAdapter = new FallbackAdapter(
      new FailingAdapter('primary'),
      new FailingAdapter('fallback'),
      { maxRetries: 2, retryDelayMs: 10 }
    );

    await fc.assert(
      fc.asyncProperty(generateOptionsArb, async (options) => {
        // 両方失敗する場合、AdapterFallbackErrorが投げられる
        await expect(bothFailingAdapter.generate(options)).rejects.toThrow(AdapterFallbackError);
      }),
      { numRuns: 30 }
    );
  });

  /**
   * Property 15.5: プライマリアダプタが成功した場合、フォールバックは使用されない
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.5: プライマリアダプタが成功した場合、フォールバックは使用されない', async () => {
    const successPrimary = new SuccessAdapter('primary');
    const successFallback = new SuccessAdapter('fallback');
    const adapter = new FallbackAdapter(successPrimary, successFallback, {
      maxRetries: 3,
      retryDelayMs: 10,
    });

    await fc.assert(
      fc.asyncProperty(generateOptionsArb, async (options) => {
        // 生成を実行
        const result = await adapter.generate(options);

        // 検証: プライマリアダプタが使用されたこと
        expect(result.content).toContain('primary');

        // 検証: フォールバックアダプタは呼び出されていないこと
        expect(successFallback.getCallCount()).toBe(0);

        // リセット
        successPrimary.resetCallCount();
        successFallback.resetCallCount();
      }),
      { numRuns: 50 }
    );
  });

  /**
   * Property 15.6: リトライ回数が設定通りに動作する
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.6: リトライ回数が設定通りに動作する', async () => {
    await fc.assert(
      fc.asyncProperty(maxRetriesArb, generateOptionsArb, async (maxRetries, options) => {
        const failingPrimary = new FailingAdapter('primary');
        const successFallback = new SuccessAdapter('fallback');
        const adapter = new FallbackAdapter(failingPrimary, successFallback, {
          maxRetries,
          retryDelayMs: 10,
        });

        // 生成を実行
        await adapter.generate(options);

        // 検証: プライマリアダプタがmaxRetries回試行されたこと
        expect(failingPrimary.getCallCount()).toBe(maxRetries);
      }),
      { numRuns: 30 }
    );
  });

  /**
   * Property 15.7: 間欠的な失敗からリトライで回復できる
   *
   * **Validates: Requirements 7.5**
   */
  it('Property 15.7: 間欠的な失敗からリトライで回復できる', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 1, max: 2 }), // 1-2回失敗してから成功
        generateOptionsArb,
        async (failuresBeforeSuccess, options) => {
          const intermittentPrimary = new IntermittentAdapter('primary', failuresBeforeSuccess);
          const successFallback = new SuccessAdapter('fallback');
          const adapter = new FallbackAdapter(intermittentPrimary, successFallback, {
            maxRetries: 3, // 3回リトライすれば成功するはず
            retryDelayMs: 10,
          });

          // 生成を実行
          const result = await adapter.generate(options);

          // 検証: プライマリアダプタが最終的に成功したこと
          expect(result.content).toContain('attempts');

          // 検証: フォールバックは使用されていないこと
          expect(successFallback.getCallCount()).toBe(0);
        }
      ),
      { numRuns: 30 }
    );
  });
});

// =============================================================================
// AdapterRegistry テスト
// =============================================================================

describe('AdapterRegistry', () => {
  let registry: AdapterRegistry;

  beforeEach(() => {
    registry = new AdapterRegistry();
  });

  afterEach(() => {
    registry.clearAdapters();
  });

  /**
   * 登録済みアダプタ名の一覧が取得できる
   */
  it('登録済みアダプタ名の一覧が取得できる', () => {
    const names = registry.getRegisteredAdapterNames();
    expect(names).toContain('ollama');
  });

  /**
   * アダプタを名前で取得できる
   */
  it('アダプタを名前で取得できる', () => {
    const adapter = registry.getAdapter('ollama');
    expect(adapter).toBeDefined();
    expect(adapter.name).toBe('ollama');
  });

  /**
   * 存在しないアダプタを取得しようとするとエラー
   */
  it('存在しないアダプタを取得しようとするとエラー', () => {
    expect(() => registry.getAdapter('nonexistent')).toThrow();
  });

  /**
   * カスタムアダプタを登録できる
   */
  it('カスタムアダプタを登録できる', () => {
    const customAdapter = new SuccessAdapter('custom');
    registry.registerAdapter('custom', customAdapter);

    const retrieved = registry.getAdapter('custom');
    expect(retrieved).toBe(customAdapter);
  });

  /**
   * デフォルトアダプタを設定・取得できる
   */
  it('デフォルトアダプタを設定・取得できる', () => {
    const defaultAdapter = registry.getDefaultAdapter();
    expect(defaultAdapter.name).toBe('ollama');
  });

  /**
   * ExtendedAdapterかどうかを判定できる
   */
  it('ExtendedAdapterかどうかを判定できる', () => {
    const adapter = registry.getAdapter('ollama');
    expect(registry.isExtendedAdapter(adapter)).toBe(true);
  });
});

// =============================================================================
// createAdapterFromConfig テスト
// =============================================================================

describe('createAdapterFromConfig', () => {
  let registry: AdapterRegistry;

  beforeEach(() => {
    registry = new AdapterRegistry();
    // テスト用アダプタを登録
    registry.registerAdapter('test-primary', new SuccessAdapter('test-primary'));
    registry.registerAdapter('test-fallback', new SuccessAdapter('test-fallback'));
  });

  afterEach(() => {
    registry.clearAdapters();
  });

  /**
   * プライマリのみの設定でアダプタを作成できる
   */
  it('プライマリのみの設定でアダプタを作成できる', () => {
    const adapter = createAdapterFromConfig({ primary: 'test-primary' }, registry);
    expect(adapter.name).toBe('test-primary');
  });

  /**
   * フォールバック付きの設定でFallbackAdapterを作成できる
   */
  it('フォールバック付きの設定でFallbackAdapterを作成できる', () => {
    const adapter = createAdapterFromConfig(
      {
        primary: 'test-primary',
        fallback: {
          fallbackAdapter: 'test-fallback',
          maxRetries: 3,
          retryDelayMs: 1000,
        },
      },
      registry
    );

    expect(adapter.name).toBe('test-primary+test-fallback');
    expect(adapter).toBeInstanceOf(FallbackAdapter);
  });
});

// =============================================================================
// エッジケースのユニットテスト
// =============================================================================

describe('AI Adapter Fallback - Edge Cases', () => {
  /**
   * 空のメッセージ配列でもchatが動作する
   */
  it('空のメッセージ配列でもchatが動作する', async () => {
    const adapter = new SuccessAdapter('test');
    const result = await adapter.chat({
      model: 'llama3',
      messages: [{ role: 'user', content: '' }],
    });
    expect(result.content).toBeDefined();
  });

  /**
   * 空のツール配列でもchatWithToolsが動作する
   */
  it('空のツール配列でもchatWithToolsが動作する', async () => {
    const adapter = new SuccessAdapter('test');
    const result = await adapter.chatWithTools({
      model: 'llama3',
      messages: [{ role: 'user', content: 'test' }],
      tools: [],
    });
    expect(result.content).toBeDefined();
    expect(result.isComplete).toBe(true);
  });

  /**
   * 日本語プロンプトが正しく処理される
   */
  it('日本語プロンプトが正しく処理される', async () => {
    const adapter = new SuccessAdapter('test');
    const result = await adapter.generate({
      model: 'llama3',
      prompt: 'これは日本語のテストプロンプトです。絵文字も含む🚀',
    });
    expect(result.content).toContain('これは日本語のテストプロンプトです');
  });

  /**
   * 非常に長いプロンプトが処理される
   */
  it('非常に長いプロンプトが処理される', async () => {
    const adapter = new SuccessAdapter('test');
    const longPrompt = 'a'.repeat(10000);
    const result = await adapter.generate({
      model: 'llama3',
      prompt: longPrompt,
    });
    expect(result.content).toBeDefined();
  });

  /**
   * FallbackAdapterのisAvailableが正しく動作する
   */
  it('FallbackAdapterのisAvailableが正しく動作する', async () => {
    // プライマリが利用可能な場合
    const adapter1 = new FallbackAdapter(
      new SuccessAdapter('primary'),
      new SuccessAdapter('fallback'),
      { maxRetries: 1, retryDelayMs: 10 }
    );
    expect(await adapter1.isAvailable()).toBe(true);

    // プライマリが利用不可、フォールバックが利用可能な場合
    const adapter2 = new FallbackAdapter(
      new FailingAdapter('primary'),
      new SuccessAdapter('fallback'),
      { maxRetries: 1, retryDelayMs: 10 }
    );
    expect(await adapter2.isAvailable()).toBe(true);

    // 両方利用不可の場合
    const adapter3 = new FallbackAdapter(
      new FailingAdapter('primary'),
      new FailingAdapter('fallback'),
      { maxRetries: 1, retryDelayMs: 10 }
    );
    expect(await adapter3.isAvailable()).toBe(false);
  });

  /**
   * FallbackAdapterのsupportsToolsが正しく動作する
   */
  it('FallbackAdapterのsupportsToolsが正しく動作する', async () => {
    const adapter = new FallbackAdapter(
      new SuccessAdapter('primary'),
      new SuccessAdapter('fallback'),
      { maxRetries: 1, retryDelayMs: 10 }
    );
    expect(adapter.supportsTools()).toBe(true);
  });

  /**
   * FallbackAdapterのgetModelInfoが正しく動作する
   */
  it('FallbackAdapterのgetModelInfoが正しく動作する', async () => {
    const adapter = new FallbackAdapter(
      new SuccessAdapter('primary'),
      new SuccessAdapter('fallback'),
      { maxRetries: 1, retryDelayMs: 10 }
    );
    const info = await adapter.getModelInfo();
    expect(info.name).toBe('primary');
    expect(info.supportsTools).toBe(true);
  });
});
